### ISSUE TITLE
Does not compile with ruby 1.9

### ISSUE THREAD

**Issue by kalkrishnan** [infinispan/ruby-client#3]
Throws a lot of errors with 1.9 and even if I get rid of the compilation errors, it does not work.
